// <auto-generated />
namespace Vidly1.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class newDtabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(newDtabase));
        
        string IMigrationMetadata.Id
        {
            get { return "202103061803209_newDtabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
